
apiVersion: apps/v1
kind: Deployment

metadata:
  name: flight-price-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flight-price-api

  template:
    metadata:
      labels:
        app: flight-price-api

    spec:
      containers:
      - name: flight-price-api
        image: voyage-analytics:latest

        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service

metadata:
  name: flight-price-service

spec:
  selector:
    app: flight-price-api

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

  type: LoadBalancer
